# Analysis configuration and paths
project_name: "gwas-handler"
version: "0.1.0"
results_dir: "/s/nath-lab/alsamman/____MyCodes____/gwashandeler/results"

# Default resources
default_resources:
  mem_mb: 64000
  cores: 2
  time: "00:30:00"

# Extraction defaults
extraction:
  delimiter: "\t"

regions: ""
target_snps: ""

# GWAS subsetting defaults
subsetting:
  pvalue_threshold: 5e-3



# Loci identification defaults
loci_identiffication:
  lead_p_threshold: 5e-8
  merge_distance_kb: 250
  use_ld: true
  auto_merge_gap_kb: 100
  ld_test_gap_min_kb: 150
  ld_test_gap_max_kb: 250
  min_snps_per_locus: 1
  require_refpanel_match: true
  chromosomes: autosomes
  min_locus_width_kbp: 1
  ld_threshold: 0.2
  n_boundary_snps: 10

gene_annotation:
  gencode_gtf: /s/nath-lab/alsamman/____MyCodes____/resources/NCBI37.3.gene.loc

# Step 8: Loci classification across datasets
classification:
  merge_gap_bp: 250000
  gws_threshold: 5e-8
  gwas_files:
    primary: ["Asian", "Asian_imp", "Disc", "Disc_imp"]
    ancestral: []

ref_panels:
  EAS: /s/nath-lab/alsamman/____MyCodes____/resources/plink_by_superpop/1kg_phase3_hg19.EAS

fuma_folder: results_OLDResults/fumas
# GWAS datasets and extraction table definitions
gwastables:
  # - name: Asian
  #   file: "input/Asian.tsv"
  #   delimiter: "\t"
  #   reference_panel: EAS
  #   tables:
  #     - table_name: gwas_primary
  #       columns: [chrom, pos, ea, nea, beta, se, p, direction, het_isq, het_chisq, het_df, het_pval, varid]

  - name: Asian_imp
    file: "input/Asian_imp.txt"
    delimiter: "\t"
    reference_panel: EAS
    tables:
      - table_name: gwas_primary
        columns: [CHR, SNP, BP, A_EFFECT, A_ALT, TYPE, Z, R2.BLUP, NEFF, P, KG_REF, KG_ALT, EAS_AF, beta_imp, se_imp, OR, L95, U95]

  # - name: Disc
  #   file: "input/Disc.tsv"
  #   delimiter: "\t"
  #   reference_panel: EAS
  #   tables:
  #     - table_name: gwas_primary
  #       columns: [chrom, pos, snpid, ea, nea, beta, se, p, direction, het_isq, het_chisq, het_df, het_pval, markername]

  - name: Disc_imp
    file: "input/Disc_imp.txt"
    delimiter: "\t"
    reference_panel: EAS
    tables:
      - table_name: gwas_primary
        columns: [CHR, SNP, BP, A_EFFECT, A_ALT, TYPE, Z, R2.BLUP, NEFF, P, MAF, beta_imp, se_imp, OR, L95, U95]